use crate::joker::{Joker, JokerState};

use crate::levels::Hand;

pub type JokerScoreFn = fn(state: &JokerState, hand: Hand) -> [f32; 3];

fn default_score(_state: &JokerState, _hand: Hand) -> [f32; 3] {
    [0.0, 0.0, 0.0]
}

pub mod _8_ball;
pub mod abstract_joker;
pub mod acrobat;
pub mod ancient_joker;
pub mod arrowhead;
pub mod astronomer;
pub mod banner;
pub mod baron;
pub mod baseball_card;
pub mod blackboard;
pub mod bloodstone;
pub mod blue_joker;
pub mod blueprint;
pub mod bootstraps;
pub mod brainstorm;
pub mod bull;
pub mod burglar;
pub mod burnt_joker;
pub mod business_card;
pub mod caino;
pub mod campfire;
pub mod card_sharp;
pub mod cartomancer;
pub mod castle;
pub mod cavendish;
pub mod ceremonial_dagger;
pub mod certificate;
pub mod chaos_the_clown;
pub mod chicot;
pub mod clever_joker;
pub mod cloud9;
pub mod constellation;
pub mod crafty_joker;
pub mod crazy_joker;
pub mod credit_card;
pub mod delayed_gratification;
pub mod devious_joker;
pub mod diet_cola;
pub mod dna;
pub mod driver_s_license;
pub mod droll_joker;
pub mod drunkard;
pub mod dusk;
pub mod egg;
pub mod erosion;
pub mod even_steven;
pub mod faceless_joker;
pub mod fibonacci;
pub mod flash_card;
pub mod flower_pot;
pub mod fortune_teller;
pub mod four_fingers;
pub mod gift_card;
pub mod glass_joker;
pub mod gluttonous_joker;
pub mod golden_joker;
pub mod golden_ticket;
pub mod greedy_joker;
pub mod green_joker;
pub mod gros_michel;
pub mod hack;
pub mod half_joker;
pub mod hallucination;
pub mod hanging_chad;
pub mod hiker;
pub mod hit_the_road;
pub mod hologram;
pub mod ice_cream;
pub mod invisible_joker;
pub mod joker;
pub mod joker_stencil;
pub mod jolly_joker;
pub mod juggler;
pub mod loyalty_card;
pub mod luchador;
pub mod lucky_cat;
pub mod lusty_joker;
pub mod mad_joker;
pub mod madness;
pub mod mail_in_rebate;
pub mod marble_joker;
pub mod matador;
pub mod merry_andy;
pub mod midas_mask;
pub mod mime;
pub mod misprint;
pub mod mr_bones;
pub mod mystic_summit;
pub mod obelisk;
pub mod odd_todd;
pub mod onyx_agate;
pub mod oops_all6s;
pub mod pareidolia;
pub mod perkeo;
pub mod photograph;
pub mod popcorn;
pub mod raised_fist;
pub mod ramen;
pub mod red_card;
pub mod reserved_parking;
pub mod ride_the_bus;
pub mod riff_raff;
pub mod rocket;
pub mod rough_gem;
pub mod runner;
pub mod satellite;
pub mod scary_face;
pub mod scholar;
pub mod seance;
pub mod seeing_double;
pub mod seltzer;
pub mod shoot_the_moon;
pub mod shortcut;
pub mod showman;
pub mod sixth_sense;
pub mod sly_joker;
pub mod smeared_joker;
pub mod smiley_face;
pub mod sock_and_buskin;
pub mod space_joker;
pub mod spare_trousers;
pub mod splash;
pub mod square_joker;
pub mod steel_joker;
pub mod stone_joker;
pub mod stuntman;
pub mod supernova;
pub mod superposition;
pub mod swashbuckler;
pub mod the_duo;
pub mod the_family;
pub mod the_idol;
pub mod the_order;
pub mod the_tribe;
pub mod the_trio;
pub mod throwback;
pub mod to_do_list;
pub mod to_the_moon;
pub mod trading_card;
pub mod triboulet;
pub mod troubadour;
pub mod turtle_bean;
pub mod vagabond;
pub mod vampire;
pub mod walkie_talkie;
pub mod wee_joker;
pub mod wily_joker;
pub mod wrathful_joker;
pub mod yorick;
pub mod zany_joker;

pub const SCORE_FNS: [JokerScoreFn; 150] = {
    let mut fns: [JokerScoreFn; 150] = [default_score; 150];
    fns[Joker::Joker as usize] = joker::score;
    fns[Joker::GreedyJoker as usize] = greedy_joker::score;
    fns[Joker::LustyJoker as usize] = lusty_joker::score;
    fns[Joker::WrathfulJoker as usize] = wrathful_joker::score;
    fns[Joker::GluttonousJoker as usize] = gluttonous_joker::score;
    fns[Joker::JollyJoker as usize] = jolly_joker::score;
    fns[Joker::ZanyJoker as usize] = zany_joker::score;
    fns[Joker::MadJoker as usize] = mad_joker::score;
    fns[Joker::CrazyJoker as usize] = crazy_joker::score;
    fns[Joker::DrollJoker as usize] = droll_joker::score;
    fns[Joker::SlyJoker as usize] = sly_joker::score;
    fns[Joker::WilyJoker as usize] = wily_joker::score;
    fns[Joker::CleverJoker as usize] = clever_joker::score;
    fns[Joker::DeviousJoker as usize] = devious_joker::score;
    fns[Joker::CraftyJoker as usize] = crafty_joker::score;
    fns[Joker::HalfJoker as usize] = half_joker::score;
    fns[Joker::JokerStencil as usize] = joker_stencil::score;
    fns[Joker::FourFingers as usize] = four_fingers::score;
    fns[Joker::Mime as usize] = mime::score;
    fns[Joker::CreditCard as usize] = credit_card::score;
    fns[Joker::CeremonialDagger as usize] = ceremonial_dagger::score;
    fns[Joker::Banner as usize] = banner::score;
    fns[Joker::MysticSummit as usize] = mystic_summit::score;
    fns[Joker::MarbleJoker as usize] = marble_joker::score;
    fns[Joker::LoyaltyCard as usize] = loyalty_card::score;
    fns[Joker::_8Ball as usize] = _8_ball::score;
    fns[Joker::Misprint as usize] = misprint::score;
    fns[Joker::Dusk as usize] = dusk::score;
    fns[Joker::RaisedFist as usize] = raised_fist::score;
    fns[Joker::ChaosTheClown as usize] = chaos_the_clown::score;
    fns[Joker::Fibonacci as usize] = fibonacci::score;
    fns[Joker::SteelJoker as usize] = steel_joker::score;
    fns[Joker::ScaryFace as usize] = scary_face::score;
    fns[Joker::AbstractJoker as usize] = abstract_joker::score;
    fns[Joker::DelayedGratification as usize] = delayed_gratification::score;
    fns[Joker::Hack as usize] = hack::score;
    fns[Joker::Pareidolia as usize] = pareidolia::score;
    fns[Joker::GrosMichel as usize] = gros_michel::score;
    fns[Joker::EvenSteven as usize] = even_steven::score;
    fns[Joker::OddTodd as usize] = odd_todd::score;
    fns[Joker::Scholar as usize] = scholar::score;
    fns[Joker::BusinessCard as usize] = business_card::score;
    fns[Joker::Supernova as usize] = supernova::score;
    fns[Joker::RideTheBus as usize] = ride_the_bus::score;
    fns[Joker::SpaceJoker as usize] = space_joker::score;
    fns[Joker::Egg as usize] = egg::score;
    fns[Joker::Burglar as usize] = burglar::score;
    fns[Joker::Blackboard as usize] = blackboard::score;
    fns[Joker::Runner as usize] = runner::score;
    fns[Joker::IceCream as usize] = ice_cream::score;
    fns[Joker::Dna as usize] = dna::score;
    fns[Joker::Splash as usize] = splash::score;
    fns[Joker::BlueJoker as usize] = blue_joker::score;
    fns[Joker::SixthSense as usize] = sixth_sense::score;
    fns[Joker::Constellation as usize] = constellation::score;
    fns[Joker::Hiker as usize] = hiker::score;
    fns[Joker::FacelessJoker as usize] = faceless_joker::score;
    fns[Joker::GreenJoker as usize] = green_joker::score;
    fns[Joker::Superposition as usize] = superposition::score;
    fns[Joker::ToDoList as usize] = to_do_list::score;
    fns[Joker::Cavendish as usize] = cavendish::score;
    fns[Joker::CardSharp as usize] = card_sharp::score;
    fns[Joker::RedCard as usize] = red_card::score;
    fns[Joker::Madness as usize] = madness::score;
    fns[Joker::SquareJoker as usize] = square_joker::score;
    fns[Joker::Seance as usize] = seance::score;
    fns[Joker::RiffRaff as usize] = riff_raff::score;
    fns[Joker::Vampire as usize] = vampire::score;
    fns[Joker::Shortcut as usize] = shortcut::score;
    fns[Joker::Hologram as usize] = hologram::score;
    fns[Joker::Vagabond as usize] = vagabond::score;
    fns[Joker::Baron as usize] = baron::score;
    fns[Joker::Cloud9 as usize] = cloud9::score;
    fns[Joker::Rocket as usize] = rocket::score;
    fns[Joker::Obelisk as usize] = obelisk::score;
    fns[Joker::MidasMask as usize] = midas_mask::score;
    fns[Joker::Luchador as usize] = luchador::score;
    fns[Joker::Photograph as usize] = photograph::score;
    fns[Joker::GiftCard as usize] = gift_card::score;
    fns[Joker::TurtleBean as usize] = turtle_bean::score;
    fns[Joker::Erosion as usize] = erosion::score;
    fns[Joker::ReservedParking as usize] = reserved_parking::score;
    fns[Joker::MailInRebate as usize] = mail_in_rebate::score;
    fns[Joker::ToTheMoon as usize] = to_the_moon::score;
    fns[Joker::Hallucination as usize] = hallucination::score;
    fns[Joker::FortuneTeller as usize] = fortune_teller::score;
    fns[Joker::Juggler as usize] = juggler::score;
    fns[Joker::Drunkard as usize] = drunkard::score;
    fns[Joker::StoneJoker as usize] = stone_joker::score;
    fns[Joker::GoldenJoker as usize] = golden_joker::score;
    fns[Joker::LuckyCat as usize] = lucky_cat::score;
    fns[Joker::BaseballCard as usize] = baseball_card::score;
    fns[Joker::Bull as usize] = bull::score;
    fns[Joker::DietCola as usize] = diet_cola::score;
    fns[Joker::TradingCard as usize] = trading_card::score;
    fns[Joker::FlashCard as usize] = flash_card::score;
    fns[Joker::Popcorn as usize] = popcorn::score;
    fns[Joker::SpareTrousers as usize] = spare_trousers::score;
    fns[Joker::AncientJoker as usize] = ancient_joker::score;
    fns[Joker::Ramen as usize] = ramen::score;
    fns[Joker::WalkieTalkie as usize] = walkie_talkie::score;
    fns[Joker::Seltzer as usize] = seltzer::score;
    fns[Joker::Castle as usize] = castle::score;
    fns[Joker::SmileyFace as usize] = smiley_face::score;
    fns[Joker::Campfire as usize] = campfire::score;
    fns[Joker::GoldenTicket as usize] = golden_ticket::score;
    fns[Joker::MrBones as usize] = mr_bones::score;
    fns[Joker::Acrobat as usize] = acrobat::score;
    fns[Joker::SockAndBuskin as usize] = sock_and_buskin::score;
    fns[Joker::Swashbuckler as usize] = swashbuckler::score;
    fns[Joker::Troubadour as usize] = troubadour::score;
    fns[Joker::Certificate as usize] = certificate::score;
    fns[Joker::SmearedJoker as usize] = smeared_joker::score;
    fns[Joker::Throwback as usize] = throwback::score;
    fns[Joker::HangingChad as usize] = hanging_chad::score;
    fns[Joker::RoughGem as usize] = rough_gem::score;
    fns[Joker::Bloodstone as usize] = bloodstone::score;
    fns[Joker::Arrowhead as usize] = arrowhead::score;
    fns[Joker::OnyxAgate as usize] = onyx_agate::score;
    fns[Joker::GlassJoker as usize] = glass_joker::score;
    fns[Joker::Showman as usize] = showman::score;
    fns[Joker::FlowerPot as usize] = flower_pot::score;
    fns[Joker::Blueprint as usize] = blueprint::score;
    fns[Joker::WeeJoker as usize] = wee_joker::score;
    fns[Joker::MerryAndy as usize] = merry_andy::score;
    fns[Joker::OopsAll6s as usize] = oops_all6s::score;
    fns[Joker::TheIdol as usize] = the_idol::score;
    fns[Joker::SeeingDouble as usize] = seeing_double::score;
    fns[Joker::Matador as usize] = matador::score;
    fns[Joker::HitTheRoad as usize] = hit_the_road::score;
    fns[Joker::TheDuo as usize] = the_duo::score;
    fns[Joker::TheTrio as usize] = the_trio::score;
    fns[Joker::TheFamily as usize] = the_family::score;
    fns[Joker::TheOrder as usize] = the_order::score;
    fns[Joker::TheTribe as usize] = the_tribe::score;
    fns[Joker::Stuntman as usize] = stuntman::score;
    fns[Joker::InvisibleJoker as usize] = invisible_joker::score;
    fns[Joker::Brainstorm as usize] = brainstorm::score;
    fns[Joker::Satellite as usize] = satellite::score;
    fns[Joker::ShootTheMoon as usize] = shoot_the_moon::score;
    fns[Joker::DriversLicense as usize] = driver_s_license::score;
    fns[Joker::Cartomancer as usize] = cartomancer::score;
    fns[Joker::Astronomer as usize] = astronomer::score;
    fns[Joker::BurntJoker as usize] = burnt_joker::score;
    fns[Joker::Bootstraps as usize] = bootstraps::score;
    fns[Joker::Canio as usize] = caino::score;
    fns[Joker::Triboulet as usize] = triboulet::score;
    fns[Joker::Yorick as usize] = yorick::score;
    fns[Joker::Chicot as usize] = chicot::score;
    fns[Joker::Perkeo as usize] = perkeo::score;

    fns
};
