#!/bin/sh

echo "Formatting code..."
cargo fmt

# Get a list of staged Rust files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rs$' || true)

if [ -n "$STAGED_FILES" ]; then
    # Re-add the staged files so that the formatted changes are included in the commit
    echo "$STAGED_FILES" | xargs git add
fi
